#!/bin/sh
module="swcsm09"
device="swcsm-pci09-"
mode="664"

# Group: since distributions do it differently, look for wheel or use staff
if grep '^staff:' /etc/group > /dev/null; then
    group="staff"
else
    group="wheel"
fi


# invoke insmod with all arguments we got
# and use a pathname, as newer modutils don't look in . by default
/sbin/insmod /lib/swcsmdrv/$module.ko $* || exit 1
# /sbin/insmod $module.ko $* || exit 1

#major=`cat /proc/devices | awk "\\$2==\"$module\" {print \\$1}"`
major="113"


# Create 8 entry points, as SHORT_NR_PORTS is 8 by default
rm -f /dev/${device}
mknod /dev/${device}0 c $major 0
mknod /dev/${device}1 c $major 1
mknod /dev/${device}2 c $major 2
mknod /dev/${device}3 c $major 3

#chgrp $group /dev/${device}[0-3]
#chmod $mode  /dev/${device}[0-3]

#chgrp $group /dev/${device}0
#chmod $mode  /dev/${device}0

